import { APP_INFO } from "@src/utils/constants";

export const unitAmenities = [
  { name: "In-Unit Washer/Dryer", icon: "Washer_Dryer.svg" },
  { name: "Refrigerator", icon: "Refrigerator.svg" },
  { name: "Stove", icon: "Stove.svg" },
  { name: "Air Conditioning", icon: "Air_Conditioning.svg" },
  { name: "Balcony", icon: "Balcony.svg" },
  { name: "Pet-Friendly", icon: "Pet-Friendly.svg" },
  { name: "Dishwasher", icon: "Dishwasher.svg" },
  { name: "Microwave", icon: "Microwave.svg" },
  { name: "Storage Room", icon: "Storage_Room.svg" },
];
export const comunityAmenities = [
  { name: "Fitness Centre", icon: "Fitness_Centre.svg" },
  { name: "Parking", icon: "Parking.svg" },
  { name: "Art Studio", icon: "Art_Studio.svg" },
  { name: "Study Room", icon: "Study_Room.svg" },
  { name: "Recycling Area", icon: "Recycling_Area.svg" },
  { name: "Bike Storage", icon: "Bike_Storage.svg" },
  { name: "Rooftop Terrace", icon: "Rooftop_Terrace.svg" },
  { name: "Keypad Entry", icon: "Keypad_Entry.svg" },
  { name: "Security Cameras", icon: "SecurityCameras.svg" },
];

export const UNIT_DETAILS = {
  title: "1 Bedroom",
  imageUrl: "/assets/img/search-property/blueprint_1.png",
  status: "Popular",
  price: "$1,815",
  amenities: [
    {
      label: "1",
      icon: "/assets/img/search-property/bed_black_icon.svg",
      alt: "Bed Icon",
    },
    {
      label: "1",
      icon: "/assets/img/search-property/bath_black_icon.svg",
      alt: "Bath Icon",
    },
    {
      icon: "/assets/img/search-property/washer_black_icon.svg",
      alt: "Washer Icon",
    },
    {
      icon: "/assets/img/search-property/wahingmachine_black_icon.svg",
      alt: "Washing Machine Icon",
    },
    {
      icon: "/assets/img/search-property/parking_black_icon.svg",
      alt: "Parking Icon",
    },
  ],
};

export const housingdetails = [
  {
    imageUrl:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    repairType: "Broken Washing Machine",
    status: "Complete",
    date: "September 15, 2025",
  },
  {
    imageUrl:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    repairType: "Broken Washing Machine",
    status: "Complete",
    date: "September 15, 2025",
  },
  {
    imageUrl:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    repairType: "Broken Washing Machine",
    status: "Complete",
    date: "September 15, 2025",
  },
  {
    imageUrl:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    repairType: "Broken Washing Machine",
    status: "Complete",
    date: "September 15, 2025",
  },
  {
    imageUrl:
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    repairType: "Broken Washing Machine",
    status: "Complete",
    date: "September 15, 2025",
  },
];
export const blogsList = [
  {
    image: `slider_1.png`,
    title: "What’s Driving Ottawa’s Rising Rental Prices in 2025?",
    date: "September 1, 2025",
    trending: true,
  },
  {
    title: "What’s Driving Ottawa’s Rising Rental Prices in 2025?",
    date: "September 1, 2025",
    trending: true,
    image: `slider_2.png`,
  },
  {
    title: "What’s Driving Ottawa’s Rising Rental Prices in 2025?",
    date: "September 1, 2025",
    trending: true,
    image: `slider_3.png`,
  },
  {
    title: "What’s Driving Ottawa’s Rising Rental Prices in 2025?",
    date: "September 1, 2025",
    trending: true,
    image: `slider_4.png`,
  },
];
export const listings = [
  {
    logo: `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/logo.png`,
    address: "211 Rideau St, Ottawa, ON K1N 5Y3",
    listingId: 2,
    title: "Studio",
    price: 1899,
    bedroomCount: 1,
    bathroomCount: 1,
    availableFrom: "Apr 30, 2025",
    checkAvailability: true,
    availableUnits: 2,
    hasParking: false,
    hasDishwasher: true,
    hasLaundry: true,
    isAccessible: false,
    hasGammingRoom: true,
    hasFitnessCenter: true,
    hasBikeStorage: true,
    hasOutDoorPatio: true,
    duration: "3 Years",
    maxNumberOfTenants: 1,
    yearBuilt: 2011,
    avgAreaCost: 2750,
    nearbyListings: 2000,
    image: `${APP_INFO.IMG_BASE_URL}/images/envoy_plan_b.jpg`,
    images: [
      `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/1.png`,
      `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/2.png`,
      `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/3.png`,
      `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/4.png`,
      `${APP_INFO.IMG_BASE_URL}/groups/Byward_Market/5.png`,
    ],
  },
  {
    logo: `${APP_INFO.IMG_BASE_URL}/groups/Theo/logo.png`,
    address: "305 Rideau St, Ottawa, ON K1N 9E5",
    listingId: 3,
    title: "Solo",
    price: 2750,
    bedroomCount: 1,
    bathroomCount: 1,
    availableFrom: "Apr 30, 2025",
    checkAvailability: true,
    availableUnits: 2,
    hasParking: false,
    hasDishwasher: true,
    hasLaundry: true,
    isAccessible: false,
    hasGammingRoom: true,
    hasFitnessCenter: true,
    hasBikeStorage: false,
    hasOutDoorPatio: false,
    hasWifi: true,
    hasArtStudio: true,
    hasPentHouseLounge: true,
    hasStudyLounge: true,
    hasFurnishedSuites: true,
    hasAccessControl: true,
    duration: "3 Years",
    maxNumberOfTenants: 1,
    yearBuilt: 2011,
    avgAreaCost: 2750,
    nearbyListings: 2900,
    image: null,
    images: [
      `${APP_INFO.IMG_BASE_URL}/groups/Theo/1.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/Theo/2.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/Theo/3.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/Theo/4.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/Theo/5.jpg`,
    ],
  },
  {
    logo: `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/logo.png`,
    address: "111 Cooper St, Ottawa, ON K2P 2E3",
    listingId: 1,
    title: "2 Bedroom",
    price: 2750,
    bedroomCount: 2, // Studio, no separate bedroom
    bathroomCount: 1,
    availableFrom: "Apr 30, 2025",
    checkAvailability: true,
    availableUnits: 2,
    hasParking: false,
    hasDishwasher: true,
    hasLaundry: true,
    isAccessible: false,
    hasGammingRoom: true,
    hasFitnessCenter: true,
    hasBikeStorage: false,
    hasOutDoorPatio: false,
    duration: "3 Years",
    maxNumberOfTenants: 1,
    yearBuilt: 2011,
    avgAreaCost: 2750,
    nearbyListings: 2900,
    image: `${APP_INFO.IMG_BASE_URL}/images/envoy_plan_c.jpg`,
    images: [
      `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/1.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/2.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/3.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/4.jpg`,
      `${APP_INFO.IMG_BASE_URL}/groups/1Eleven/5.jpg`,
    ],
  },
];
